services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
 #   ports:
 #     - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    #command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    command: sh -c "python3 manage.py migrate && uwsgi uwsgi.ini"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db